<?php

namespace ContainerTWxebRA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DSPzpZLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dSPzpZL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dSPzpZL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminSkillsController::deleteskill' => ['privates', '.service_locator.cRsZBpf', 'get_ServiceLocator_CRsZBpfService', true],
            'App\\Controller\\AdminSkillsController::index' => ['privates', '.service_locator.cRsZBpf', 'get_ServiceLocator_CRsZBpfService', true],
            'App\\Controller\\AdminSkillsController::updateSkill' => ['privates', '.service_locator.cRsZBpf', 'get_ServiceLocator_CRsZBpfService', true],
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.QpY9.ko', 'get_ServiceLocator_QpY9_KoService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.cRsZBpf', 'get_ServiceLocator_CRsZBpfService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.LeCcMXp', 'get_ServiceLocator_LeCcMXpService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.Tvd7vqW', 'get_ServiceLocator_Tvd7vqWService', true],
            'App\\Controller\\TranslationController::changeLocale' => ['privates', '.service_locator.wccMqx5', 'get_ServiceLocator_WccMqx5Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.Bv1nHN9', 'get_ServiceLocator_Bv1nHN9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'kernel::terminate' => ['privates', '.service_locator.Bv1nHN9', 'get_ServiceLocator_Bv1nHN9Service', true],
            'App\\Controller\\AdminSkillsController:deleteskill' => ['privates', '.service_locator.cRsZBpf', 'get_ServiceLocator_CRsZBpfService', true],
            'App\\Controller\\AdminSkillsController:index' => ['privates', '.service_locator.cRsZBpf', 'get_ServiceLocator_CRsZBpfService', true],
            'App\\Controller\\AdminSkillsController:updateSkill' => ['privates', '.service_locator.cRsZBpf', 'get_ServiceLocator_CRsZBpfService', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.QpY9.ko', 'get_ServiceLocator_QpY9_KoService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.cRsZBpf', 'get_ServiceLocator_CRsZBpfService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.LeCcMXp', 'get_ServiceLocator_LeCcMXpService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.Tvd7vqW', 'get_ServiceLocator_Tvd7vqWService', true],
            'App\\Controller\\TranslationController:changeLocale' => ['privates', '.service_locator.wccMqx5', 'get_ServiceLocator_WccMqx5Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.7F3oxVY', 'get_ServiceLocator_7F3oxVYService', true],
            'kernel:terminate' => ['privates', '.service_locator.Bv1nHN9', 'get_ServiceLocator_Bv1nHN9Service', true],
        ], [
            'App\\Controller\\AdminSkillsController::deleteskill' => '?',
            'App\\Controller\\AdminSkillsController::index' => '?',
            'App\\Controller\\AdminSkillsController::updateSkill' => '?',
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\TranslationController::changeLocale' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminSkillsController:deleteskill' => '?',
            'App\\Controller\\AdminSkillsController:index' => '?',
            'App\\Controller\\AdminSkillsController:updateSkill' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\TranslationController:changeLocale' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
