<?php

namespace ContainerU1vSPKf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__S6y2x7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..s6y2x7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..s6y2x7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminSkillsController::deleteskill' => ['privates', '.service_locator.oH5CAGz', 'get_ServiceLocator_OH5CAGzService', true],
            'App\\Controller\\AdminSkillsController::index' => ['privates', '.service_locator.oH5CAGz', 'get_ServiceLocator_OH5CAGzService', true],
            'App\\Controller\\AdminSkillsController::updateSkill' => ['privates', '.service_locator.oH5CAGz', 'get_ServiceLocator_OH5CAGzService', true],
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.ff7a1x0', 'get_ServiceLocator_Ff7a1x0Service', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.oH5CAGz', 'get_ServiceLocator_OH5CAGzService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.0wS_xAA', 'get_ServiceLocator_0wSXAAService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\TranslationController::changeLocale' => ['privates', '.service_locator.q2ji3lu', 'get_ServiceLocator_Q2ji3luService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AdminSkillsController:deleteskill' => ['privates', '.service_locator.oH5CAGz', 'get_ServiceLocator_OH5CAGzService', true],
            'App\\Controller\\AdminSkillsController:index' => ['privates', '.service_locator.oH5CAGz', 'get_ServiceLocator_OH5CAGzService', true],
            'App\\Controller\\AdminSkillsController:updateSkill' => ['privates', '.service_locator.oH5CAGz', 'get_ServiceLocator_OH5CAGzService', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.ff7a1x0', 'get_ServiceLocator_Ff7a1x0Service', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.oH5CAGz', 'get_ServiceLocator_OH5CAGzService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.0wS_xAA', 'get_ServiceLocator_0wSXAAService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\TranslationController:changeLocale' => ['privates', '.service_locator.q2ji3lu', 'get_ServiceLocator_Q2ji3luService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AdminSkillsController::deleteskill' => '?',
            'App\\Controller\\AdminSkillsController::index' => '?',
            'App\\Controller\\AdminSkillsController::updateSkill' => '?',
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\TranslationController::changeLocale' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminSkillsController:deleteskill' => '?',
            'App\\Controller\\AdminSkillsController:index' => '?',
            'App\\Controller\\AdminSkillsController:updateSkill' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\TranslationController:changeLocale' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
