<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerILKQTnj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerILKQTnj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerILKQTnj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerILKQTnj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerILKQTnj\App_KernelDevDebugContainer([
    'container.build_hash' => 'ILKQTnj',
    'container.build_id' => '6a413076',
    'container.build_time' => 1694611012,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerILKQTnj');
