<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPhxesrp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPhxesrp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPhxesrp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPhxesrp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPhxesrp\App_KernelDevDebugContainer([
    'container.build_hash' => 'Phxesrp',
    'container.build_id' => '1cb10029',
    'container.build_time' => 1695135608,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPhxesrp');
